---
- name: Check if the Dynatrace Client installer is provided locally
  local_action: stat path="{{ playbook_dir }}/roles/{{ dynatrace_client_role_name }}/files/linux/{{ dynatrace_client_linux_installer_file_name }}"
  register: dynatrace_client_installer_provided

- name: Fail if the Dynatrace Client installer is not provided locally
  fail: msg="The Dynatrace Client installer is not provided at {{ playbook_dir }}/roles/{{ dynatrace_client_role_name }}/files/linux/{{ dynatrace_client_linux_installer_file_name }}."
  when: not dynatrace_client_installer_provided.stat.exists

- include: linux/install-dependencies-apt.yml
  when: dynatrace_client_installer_provided.stat.exists and ansible_pkg_mgr == "apt"
- include: linux/install-dependencies-yum.yml
  when: dynatrace_client_installer_provided.stat.exists and ansible_pkg_mgr == "yum"

- include: linux/install-dynatrace-user.yml
  when: dynatrace_client_installer_provided.stat.exists

- include: linux/install-dynatrace-client.yml
  when: dynatrace_client_installer_provided.stat.exists

- include: linux/remove-dependencies-apt.yml
  when: dynatrace_client_installer_provided.stat.exists and ansible_pkg_mgr == "apt"
- include: linux/remove-dependencies-yum.yml
  when: dynatrace_client_installer_provided.stat.exists and ansible_pkg_mgr == "yum"
